version: '3.8'

services:
  super-skylab-app:
    build: .
    ports:
      - "9010:9010"
    depends_on:
      - db
    networks:
        - nginx-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: superSkyLabDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5455:5455"
    networks:
        - nginx-network

networks:
  nginx-network:
    external: true